formatter: "markdown table"

output:
  file: "README.md"
  mode: replace

sections:
  show:
    - header

content: |-
  <h1 style="font-size: 2.5em; font-weight: bold; margin-bottom: 20px;">Slack Provider</h1>
  {{ regexReplaceAll "(?s)\\A---\\n.*?\\n---\\n" (include "docs/index.md") "" }}
  <br>
  <br>
  <br>
  <h1 style="font-size: 2.5em; font-weight: bold; margin-bottom: 20px;">Data Sources</h1>
  {{ regexReplaceAll "(?s)\\A---\\n.*?\\n---\\n" (include "docs/data-sources/user.md") "" }}
  <br>
  <br>
  <br>
  {{ regexReplaceAll "(?s)\\A---\\n.*?\\n---\\n" (include "docs/data-sources/user_ids.md") "" }}
  <br>
  <br>
  <br>
  <h1 style="font-size: 2.5em; font-weight: bold; margin-bottom: 20px;">Resources</h1>
  {{ regexReplaceAll "(?s)\\A---\\n.*?\\n---\\n" (include "docs/resources/message.md") "" }}
